phone/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('phone', 'PhoneController');
Route::resource('type', 'TypeController');

phone/app/Phone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
  public function user() {
    return $this->hasOne('App\User', 'id', 'user_id');
  }

  public function type() {
    return $this->hasOne('App\Type', 'id', 'type_id');
  }
}

phone/app/Type.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Type extends Model
{
    //
}

phone/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

phone/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

phone/app/Http/Controllers/PhoneController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Phone;
use App\Type;
use App\User;

class PhoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $phones = Phone::all();
        $types = Type::all();
        $users = User::all();
        return view('phone/index',  compact('phones', 'types', 'users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return dump($request);
        $phone = new Phone;
        $phone->number = $request->number;
        $phone->user_id = $request->user_id;
        $phone->type_id = $request->type_id;
        $phone->save();
        return redirect(route('phone.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $phone = Phone::where('id', $id)->first();
        $types = Type::all();
        $users = User::all();
        return view('phone/edit',  compact('phone', 'types', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $phone = Phone::where('id', $id)->first();
        $phone->number = $request->number;
        $phone->user_id = $request->user_id;
        $phone->type_id = $request->type_id;
        $phone->save();
        return redirect(route('phone.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Phone::where('id',$id)->delete();
        return redirect( route('phone.index') );
    }
}

phone/app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Type;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $type = new Type;
        $type->name = $request->name;
        $type->save();
        return redirect(route('phone.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $phones = Phone::where('type_id', $id)->get();
        foreach($phone as $phones) {
            $phone->type_id = 2
            $phone->save();
        }
        Type::where('id',$id)->delete();
        return redirect( route('phone.index') );
    }
}

phone/resources/views/phone/edit.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Номера телефонов</title>
</head>
<body>
  <div class="col-12">
    <h1 class="text-center">Лабораторная работы 9</h1>
  </div>
  <div class="container">
    <div class="row mt-3">
      <div class="col-6 offset-3">
        <form method="post" action="{{ route('phone.update', $phone->id) }}">
          @method('PUT')
          <div class="form-group">
            <label for="exampleFormControlInput1">Номер телефона</label>
            <input type="text" class="form-control" name='number' placeholder="Номер телефона" value="{{ $phone->number }}">
          </div>
          <div class="form-group">
            <label for="exampleFormControlSelect2">Пользователь</label>
              <select class="form-control" name='user_id' id="exampleFormControlSelect2">
                @foreach ($users as $user)
                  <option value='{{ $user->id }}'
                    @if ($phone->user_id === $user->id)
                      selected
                    @endif
                  >{{ $user->name }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
            <label for="exampleFormControlSelect2">Тип телефона</label>
              <select class="form-control" name='type_id' id="exampleFormControlSelect2">
                @foreach ($types as $type)
                  <option value='{{ $type->id }}'
                    @if ($type->id === $phone->type_id)
                    selected
                    @endif
                    >{{ $type->name }}</option>
                @endforeach
              </select>
          </div>
          <button type="submit" class="btn btn-primary mb-2">Сохранить</button>
          @csrf
        </form>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

phone/resources/views/phone/index.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Номера телефонов</title>
</head>
<body>
  <div class="col-12">
    <h1 class="text-center">Лабораторная работы 9</h1>
  </div>
  <div class="container">
    <div class="row mt-5">
      <div class="col-4">
        <div class="list-group" id="list-tab" role="tablist">
          @forelse ($phones as $phone)
          <a class="list-group-item list-group-item-action" id="list-<?=$phone->id?>" data-toggle="list" href="#list-home-<?=$phone->id?>" role="tab" aria-controls="home">{{ $phone->number }}</a>
          @empty
            <p>Нет контактов</p>
          @endforelse
        </div>
      </div>
      <div class="col-8">
        <div class="tab-content" id="nav-tabContent">
          @forelse ($phones as $phone)
            <div class="tab-pane fade" id="list-home-<?=$phone->id?>" role="tabpanel" aria-labelledby="list-<?=$phone->id?>">
              <p>Имя: {{ $phone->user->name }}</p>
              <p>Почта: {{ $phone->user->email }}</p>
              <p>Тип: {{ $phone->type->name }}</p>
              <a href="{{ route('phone.edit', $phone->id) }}" class="btn btn-warning my-1">Редактировать</a>
              <form action="{{ route('phone.destroy', $phone->id) }}" method='post'>
                <button type="submit" class='btn btn-danger'>Удалить</button>
                @method('DELETE')
                @csrf
              </form>
            </div>
          @empty
            <p>Нет контактов</p>
          @endforelse
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row mt-4">
        <div class="col-6 offset-3">
          <form method="post" action="{{ route('phone.store') }}">
            <div class="form-group">
              <label for="exampleFormControlInput1">Номер телефона</label>
              <input type="text" class="form-control" name='number' placeholder="Номер телефона">
            </div>
            <div class="form-group">
              <label for="exampleFormControlSelect2">Пользователь</label>
                <select class="form-control" name='user_id' id="exampleFormControlSelect2">
                  @foreach ($users as $user)
                    <option value='{{ $user->id }}'>{{ $user->name }}</option>
                  @endforeach
                </select>
            </div>
            <div class="form-group">
              <label for="exampleFormControlSelect2">Тип телефона</label>
                <select class="form-control" name='type_id' id="exampleFormControlSelect2">
                  @foreach ($types as $type)
                    <option value='{{ $type->id }}'>{{ $type->name }}</option>
                  @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Сохранить</button>
            @csrf
          </form>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row mt-4">
        <div class="col-6 offset-3">
          <form method="post" action="{{ route('type.store') }}">
            <div class="form-group">
              <label for="exampleFormControlInput1">Наименование</label>
              <input type="text" class="form-control" name='name' placeholder="Наименование">
            </div>
            <button type="submit" class="btn btn-primary mb-2">Сохранить</button>
            @csrf
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>